//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shipmonitoring.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("shipmonitoring.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sambungkan.
        /// </summary>
        internal static string button_koneksi_terputus {
            get {
                return ResourceManager.GetString("button_koneksi_terputus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putuskan.
        /// </summary>
        internal static string button_koneksi_tersambung {
            get {
                return ResourceManager.GetString("button_koneksi_tersambung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siap untuk disambungkan.
        /// </summary>
        internal static string koneksi_siap {
            get {
                return ResourceManager.GetString("koneksi_siap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koneksi Terputus.
        /// </summary>
        internal static string koneksi_terputus {
            get {
                return ResourceManager.GetString("koneksi_terputus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tersambung.
        /// </summary>
        internal static string koneksi_tersambung {
            get {
                return ResourceManager.GetString("koneksi_tersambung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berhasil membaca Database.
        /// </summary>
        internal static string warning_database_baca_berhasil {
            get {
                return ResourceManager.GetString("warning_database_baca_berhasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagal membaca Database.
        /// </summary>
        internal static string warning_database_baca_gagal {
            get {
                return ResourceManager.GetString("warning_database_baca_gagal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berhasil menghubungkan ke Database.
        /// </summary>
        internal static string warning_database_koneksi_berhasil {
            get {
                return ResourceManager.GetString("warning_database_koneksi_berhasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagal menghubungkan ke Database.
        /// </summary>
        internal static string warning_database_koneksi_gagal {
            get {
                return ResourceManager.GetString("warning_database_koneksi_gagal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berhasil menyimpan ke Database.
        /// </summary>
        internal static string warning_database_simpan_berhasil {
            get {
                return ResourceManager.GetString("warning_database_simpan_berhasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagal menyimpan ke Database.
        /// </summary>
        internal static string warning_database_simpan_gagal {
            get {
                return ResourceManager.GetString("warning_database_simpan_gagal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berhasil menyambungkan.
        /// </summary>
        internal static string warning_koneksi_berhasil {
            get {
                return ResourceManager.GetString("warning_koneksi_berhasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gagal menyambungkan.
        /// </summary>
        internal static string warning_koneksi_gagal {
            get {
                return ResourceManager.GetString("warning_koneksi_gagal", resourceCulture);
            }
        }
    }
}
